app:
  config:
    source:
      file:
        connection_string: 
          file_path: "C:\\Users\\Girish-Nair\\Documents\\testingpyinstaller\\data.csv"
      database:
        connection_string: 
          database_name: local_postgres
          host: localhost
          port: 5432
          username: postgres
          password: root
    target:
      file:
        connection_string: 
          file_path: "C:\\Users\\Girish-Nair\\Documents\\testingpyinstaller\\data.csv"
      database:
        connection_string: 
          database_name: local_postgres
          host: localhost
          port: 5432
          username: postgres
          password: root