app:
  config:
    file:
      connection_string: 
        file_path: "C:\\Users\\Girish-Nair\\Documents\\testingpyinstaller\\data.csv"
    database:
      connection_string: 
        database_name: postgres
        host: localhost
        port: 50520
        username: postgres
        password: root